"""add patient, medication, prescription, episode, clinical_note, clinical_document models

Revision ID: 2c11cc95877d
Revises: 
Create Date: 2026-06-18 19:38:33.905339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c11cc95877d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=False),
    sa.Column('brand_names', sa.JSON(), nullable=False),
    sa.Column('atc_code', sa.String(length=10), nullable=False),
    sa.Column('atc_levels', sa.JSON(), nullable=False),
    sa.Column('therapeutic_class', sa.String(length=100), nullable=False),
    sa.Column('pharmacological_class', sa.String(length=100), nullable=False),
    sa.Column('active_ingredients', sa.JSON(), nullable=False),
    sa.Column('presentations', sa.JSON(), nullable=False),
    sa.Column('standard_dosage', sa.JSON(), nullable=False),
    sa.Column('indications', sa.JSON(), nullable=False),
    sa.Column('contraindications', sa.JSON(), nullable=False),
    sa.Column('precautions', sa.JSON(), nullable=False),
    sa.Column('pregnancy_category', sa.Enum('A', 'B', 'C', 'D', 'X', 'N', name='pregnancycategory'), nullable=False),
    sa.Column('lactation_category', sa.Enum('L1', 'L2', 'L3', 'L4', 'L5', name='lactationcategory'), nullable=False),
    sa.Column('pregnancy_notes', sa.Text(), nullable=True),
    sa.Column('lactation_notes', sa.Text(), nullable=True),
    sa.Column('half_life_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('bioavailability', sa.String(length=50), nullable=True),
    sa.Column('protein_binding', sa.String(length=50), nullable=True),
    sa.Column('metabolism', sa.Text(), nullable=True),
    sa.Column('excretion', sa.Text(), nullable=True),
    sa.Column('monitoring_parameters', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISCONTINUED', 'EXPERIMENTAL', 'WITHDRAWN', name='medicationstatus'), nullable=False),
    sa.Column('is_controlled', sa.Boolean(), nullable=False),
    sa.Column('controlled_schedule', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generic_name', 'atc_code', name='uq_medication_generic_atc')
    )
    op.create_index('ix_medications_atc_class', 'medications', ['atc_code', 'therapeutic_class'], unique=False)
    op.create_index(op.f('ix_medications_atc_code'), 'medications', ['atc_code'], unique=False)
    op.create_index('ix_medications_generic_active', 'medications', ['generic_name', 'status'], unique=False)
    op.create_index(op.f('ix_medications_generic_name'), 'medications', ['generic_name'], unique=False)
    op.create_index(op.f('ix_medications_therapeutic_class'), 'medications', ['therapeutic_class'], unique=False)
    op.create_table('drug_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medication_a_id', sa.Integer(), nullable=False),
    sa.Column('medication_b_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=False),
    sa.Column('clinical_effect', sa.Text(), nullable=False),
    sa.Column('management', sa.Text(), nullable=False),
    sa.Column('evidence_level', sa.String(length=20), nullable=True),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('is_bidirectional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['medication_a_id'], ['medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medication_b_id'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medication_a_id', 'medication_b_id', name='uq_interaction_pair')
    )
    op.create_index(op.f('ix_drug_interactions_medication_a_id'), 'drug_interactions', ['medication_a_id'], unique=False)
    op.create_index(op.f('ix_drug_interactions_medication_b_id'), 'drug_interactions', ['medication_b_id'], unique=False)
    op.create_index(op.f('ix_drug_interactions_severity'), 'drug_interactions', ['severity'], unique=False)
    op.create_index('ix_interactions_severity', 'drug_interactions', ['severity'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sex'), nullable=False),
    sa.Column('blood_type', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', 'UNKNOWN', name='bloodtype'), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('drug_allergies', sa.JSON(), nullable=False),
    sa.Column('chronic_conditions', sa.JSON(), nullable=False),
    sa.Column('current_medications', sa.JSON(), nullable=False),
    sa.Column('surgical_history', sa.JSON(), nullable=False),
    sa.Column('family_history', sa.JSON(), nullable=False),
    sa.Column('immunizations', sa.JSON(), nullable=False),
    sa.Column('baseline_bp_systolic', sa.Integer(), nullable=True),
    sa.Column('baseline_bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('baseline_heart_rate', sa.Integer(), nullable=True),
    sa.Column('baseline_temperature', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('baseline_spo2', sa.Integer(), nullable=True),
    sa.Column('baseline_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('baseline_height', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vitals_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('smoking_status', sa.String(length=20), nullable=True),
    sa.Column('alcohol_use', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patients_clinician_active', 'patients', ['clinician_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_patients_clinician_id'), 'patients', ['clinician_id'], unique=False)
    op.create_index(op.f('ix_patients_date_of_birth'), 'patients', ['date_of_birth'], unique=False)
    op.create_index('ix_patients_dob_sex', 'patients', ['date_of_birth', 'sex'], unique=False)
    op.create_index('ix_patients_name_search', 'patients', ['first_name', 'last_name'], unique=False)
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=True)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=True),
    sa.Column('episode_type', sa.Enum('EMERGENCY', 'CONSULTATION', 'HOSPITALIZATION', 'TELEMEDICINE', 'HOME_VISIT', 'PREOPERATIVE', 'POSTOPERATIVE', 'FOLLOWUP', 'SCREENING', 'VACCINATION', name='episodetype'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'ON_HOLD', 'CLOSED', 'CANCELLED', 'REFERRED', name='episodestatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('reason_for_visit', sa.Text(), nullable=True),
    sa.Column('subjective', sa.JSON(), nullable=False),
    sa.Column('objective', sa.JSON(), nullable=False),
    sa.Column('assessment', sa.JSON(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('diagnoses', sa.JSON(), nullable=False),
    sa.Column('procedures', sa.JSON(), nullable=False),
    sa.Column('is_billable', sa.Boolean(), nullable=False),
    sa.Column('requires_followup', sa.Boolean(), nullable=False),
    sa.Column('followup_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_episodes_clinician_date', 'episodes', ['clinician_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_episodes_clinician_id'), 'episodes', ['clinician_id'], unique=False)
    op.create_index(op.f('ix_episodes_patient_id'), 'episodes', ['patient_id'], unique=False)
    op.create_index('ix_episodes_patient_status', 'episodes', ['patient_id', 'status'], unique=False)
    op.create_index('ix_episodes_patient_type_date', 'episodes', ['patient_id', 'episode_type', 'started_at'], unique=False)
    op.create_index('ix_episodes_status_date', 'episodes', ['status', 'started_at'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=True),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('route', sa.String(length=20), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('refills_allowed', sa.Integer(), nullable=False),
    sa.Column('refills_used', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('indication', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'DISCONTINUED', 'ON_HOLD', 'EXPIRED', 'REFILL_EXHAUSTED', name='prescriptionstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('last_dispensed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispensed_quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_clinician_id'), 'prescriptions', ['clinician_id'], unique=False)
    op.create_index('ix_prescriptions_clinician_status', 'prescriptions', ['clinician_id', 'status'], unique=False)
    op.create_index(op.f('ix_prescriptions_medication_id'), 'prescriptions', ['medication_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_index('ix_prescriptions_patient_med_status', 'prescriptions', ['patient_id', 'medication_id', 'status'], unique=False)
    op.create_index('ix_prescriptions_patient_status', 'prescriptions', ['patient_id', 'status'], unique=False)
    op.create_table('vital_signs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bmi', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'DEVICE', 'IMPORT', name='vitalsource'), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vital_signs_measured_at'), 'vital_signs', ['measured_at'], unique=False)
    op.create_index(op.f('ix_vital_signs_patient_id'), 'vital_signs', ['patient_id'], unique=False)
    op.create_index('ix_vital_signs_patient_measured', 'vital_signs', ['patient_id', 'measured_at'], unique=False)
    op.create_index('ix_vital_signs_patient_source', 'vital_signs', ['patient_id', 'source'], unique=False)
    op.create_table('clinical_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_documents_episode_id'), 'clinical_documents', ['episode_id'], unique=False)
    op.create_table('clinical_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=False),
    sa.Column('is_signed', sa.Boolean(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_notes_author_id'), 'clinical_notes', ['author_id'], unique=False)
    op.create_index('ix_clinical_notes_episode_created', 'clinical_notes', ['episode_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_clinical_notes_episode_id'), 'clinical_notes', ['episode_id'], unique=False)
    op.add_column('users', sa.Column('totp_secret', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('backup_codes', sa.JSON(), nullable=False, server_default='[]'))
    # Skip alter_column for users table - SQLite doesn't support ALTER COLUMN with Enum/change type
    # op.alter_column('users', 'rol',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.Enum('ADMIN', 'CLINICIAN', 'PATIENT', name='userrole'),
    #            nullable=False)
    # op.alter_column('users', 'activo',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip alter_column for users table - SQLite doesn't support it
    # op.alter_column('users', 'activo',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True)
    # op.alter_column('users', 'rol',
    #            existing_type=sa.Enum('ADMIN', 'CLINICIAN', 'PATIENT', name='userrole'),
    #            type_=sa.VARCHAR(length=50),
    #            nullable=True)
    op.drop_column('users', 'backup_codes')
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    op.drop_index(op.f('ix_clinical_notes_episode_id'), table_name='clinical_notes')
    op.drop_index('ix_clinical_notes_episode_created', table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_author_id'), table_name='clinical_notes')
    op.drop_table('clinical_notes')
    op.drop_index(op.f('ix_clinical_documents_episode_id'), table_name='clinical_documents')
    op.drop_table('clinical_documents')
    op.drop_index('ix_vital_signs_patient_source', table_name='vital_signs')
    op.drop_index('ix_vital_signs_patient_measured', table_name='vital_signs')
    op.drop_index(op.f('ix_vital_signs_patient_id'), table_name='vital_signs')
    op.drop_index(op.f('ix_vital_signs_measured_at'), table_name='vital_signs')
    op.drop_table('vital_signs')
    op.drop_index('ix_prescriptions_patient_status', table_name='prescriptions')
    op.drop_index('ix_prescriptions_patient_med_status', table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_medication_id'), table_name='prescriptions')
    op.drop_index('ix_prescriptions_clinician_status', table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_clinician_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index('ix_episodes_status_date', table_name='episodes')
    op.drop_index('ix_episodes_patient_type_date', table_name='episodes')
    op.drop_index('ix_episodes_patient_status', table_name='episodes')
    op.drop_index(op.f('ix_episodes_patient_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_clinician_id'), table_name='episodes')
    op.drop_index('ix_episodes_clinician_date', table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_patients_user_id'), table_name='patients')
    op.drop_index('ix_patients_name_search', table_name='patients')
    op.drop_index('ix_patients_dob_sex', table_name='patients')
    op.drop_index(op.f('ix_patients_date_of_birth'), table_name='patients')
    op.drop_index(op.f('ix_patients_clinician_id'), table_name='patients')
    op.drop_index('ix_patients_clinician_active', table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_interactions_severity', table_name='drug_interactions')
    op.drop_index(op.f('ix_drug_interactions_severity'), table_name='drug_interactions')
    op.drop_index(op.f('ix_drug_interactions_medication_b_id'), table_name='drug_interactions')
    op.drop_index(op.f('ix_drug_interactions_medication_a_id'), table_name='drug_interactions')
    op.drop_table('drug_interactions')
    op.drop_index(op.f('ix_medications_therapeutic_class'), table_name='medications')
    op.drop_index(op.f('ix_medications_generic_name'), table_name='medications')
    op.drop_index('ix_medications_generic_active', table_name='medications')
    op.drop_index(op.f('ix_medications_atc_code'), table_name='medications')
    op.drop_index('ix_medications_atc_class', table_name='medications')
    op.drop_table('medications')
    # ### end Alembic commands ###
